export enum Event {
  SEARCHING_MATCH = "SEARCHING_MATCH",
  OPPONENT_ASSIGNED = "OPPONENT_ASSIGNED",
  OPPONENT_READY = "OPPONENT_READY",

  UPDATE_SHIPS = "UPDATE_SHIPS",

  $$SETTINGS = "$$settings",
}

export enum ServerEvent {
  PING = "PING",
  PONG = "PONG",

  USER_JOIN = "USER_JOIN",
  USER_LEAVE = "USER_LEAVE",
  USER_DATA = "USER_DATA",
  USER_READY = "USER_READY",

  USER_REWARD = "USER_REWARD",

  DISCONNECT_USER = "DISCONNECT_USER",
}
