export enum Event {
  SEARCHING_MATCH = "SEARCHING_MATCH",
  OPPONENT_ASSIGNED = "OPPONENT_ASSIGNED",
  OPPONENT_READY = "OPPONENT_READY",

  UPDATE_SHIPS = "UPDATE_SHIPS",

  $$SETTINGS = "$$settings",
}
