export enum Event {
  SEARCHING_MATCH = "SEARCHING_MATCH",
  OPPONENT_ASSIGNED = "OPPONENT_ASSIGNED",
  OPPONENT_READY = "OPPONENT_READY",

  READY_PLACING = "READY_PLACING",

  $$SETTINGS = "$$settings",
}
